// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: protos/resolver.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *ResolverRequest) Reset() {
	*x = ResolverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_resolver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolverRequest) ProtoMessage() {}

func (x *ResolverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_resolver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolverRequest.ProtoReflect.Descriptor instead.
func (*ResolverRequest) Descriptor() ([]byte, []int) {
	return file_protos_resolver_proto_rawDescGZIP(), []int{0}
}

func (x *ResolverRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type ResolverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DidDocument string `protobuf:"bytes,1,opt,name=didDocument,proto3" json:"didDocument,omitempty"`
}

func (x *ResolverResponse) Reset() {
	*x = ResolverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_resolver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolverResponse) ProtoMessage() {}

func (x *ResolverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_resolver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolverResponse.ProtoReflect.Descriptor instead.
func (*ResolverResponse) Descriptor() ([]byte, []int) {
	return file_protos_resolver_proto_rawDescGZIP(), []int{1}
}

func (x *ResolverResponse) GetDidDocument() string {
	if x != nil {
		return x.DidDocument
	}
	return ""
}

var File_protos_resolver_proto protoreflect.FileDescriptor

var file_protos_resolver_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x72, 0x22, 0x23, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69,
	0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x69, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0x51, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x44, 0x69, 0x64, 0x12, 0x19, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0e, 0x5a, 0x0c, 0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_resolver_proto_rawDescOnce sync.Once
	file_protos_resolver_proto_rawDescData = file_protos_resolver_proto_rawDesc
)

func file_protos_resolver_proto_rawDescGZIP() []byte {
	file_protos_resolver_proto_rawDescOnce.Do(func() {
		file_protos_resolver_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_resolver_proto_rawDescData)
	})
	return file_protos_resolver_proto_rawDescData
}

var file_protos_resolver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_resolver_proto_goTypes = []interface{}{
	(*ResolverRequest)(nil),  // 0: resolver.ResolverRequest
	(*ResolverResponse)(nil), // 1: resolver.ResolverResponse
}
var file_protos_resolver_proto_depIdxs = []int32{
	0, // 0: resolver.Resolver.ResolveDid:input_type -> resolver.ResolverRequest
	1, // 1: resolver.Resolver.ResolveDid:output_type -> resolver.ResolverResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_resolver_proto_init() }
func file_protos_resolver_proto_init() {
	if File_protos_resolver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_resolver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_resolver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_resolver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_resolver_proto_goTypes,
		DependencyIndexes: file_protos_resolver_proto_depIdxs,
		MessageInfos:      file_protos_resolver_proto_msgTypes,
	}.Build()
	File_protos_resolver_proto = out.File
	file_protos_resolver_proto_rawDesc = nil
	file_protos_resolver_proto_goTypes = nil
	file_protos_resolver_proto_depIdxs = nil
}
