// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: protos/resolver.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Resolver_ResolveDid_FullMethodName = "/resolver.Resolver/ResolveDid"
)

// ResolverClient is the client API for Resolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResolverClient interface {
	ResolveDid(ctx context.Context, in *ResolverRequest, opts ...grpc.CallOption) (*ResolverResponse, error)
}

type resolverClient struct {
	cc grpc.ClientConnInterface
}

func NewResolverClient(cc grpc.ClientConnInterface) ResolverClient {
	return &resolverClient{cc}
}

func (c *resolverClient) ResolveDid(ctx context.Context, in *ResolverRequest, opts ...grpc.CallOption) (*ResolverResponse, error) {
	out := new(ResolverResponse)
	err := c.cc.Invoke(ctx, Resolver_ResolveDid_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResolverServer is the server API for Resolver service.
// All implementations must embed UnimplementedResolverServer
// for forward compatibility
type ResolverServer interface {
	ResolveDid(context.Context, *ResolverRequest) (*ResolverResponse, error)
	mustEmbedUnimplementedResolverServer()
}

// UnimplementedResolverServer must be embedded to have forward compatible implementations.
type UnimplementedResolverServer struct {
}

func (UnimplementedResolverServer) ResolveDid(context.Context, *ResolverRequest) (*ResolverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveDid not implemented")
}
func (UnimplementedResolverServer) mustEmbedUnimplementedResolverServer() {}

// UnsafeResolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResolverServer will
// result in compilation errors.
type UnsafeResolverServer interface {
	mustEmbedUnimplementedResolverServer()
}

func RegisterResolverServer(s grpc.ServiceRegistrar, srv ResolverServer) {
	s.RegisterService(&Resolver_ServiceDesc, srv)
}

func _Resolver_ResolveDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).ResolveDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_ResolveDid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).ResolveDid(ctx, req.(*ResolverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Resolver_ServiceDesc is the grpc.ServiceDesc for Resolver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Resolver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resolver.Resolver",
	HandlerType: (*ResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveDid",
			Handler:    _Resolver_ResolveDid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/resolver.proto",
}
